import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import HeroPage from "./components/Hero";
import SliderPage from "./components/Slider";
import { SliderData } from "./components/SliderData";
import InstagramPage from "./components/Instagram";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photo Next App</title>
        <meta name="description" content="Generated by photo-next." />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroPage
        heading="Captur Photography"
        message="I capture moments in nature and keep them alive."
      />
      <SliderPage slides={SliderData} />
      <InstagramPage />
    </div>
  );
}
